races_2018 = [
    (1, "Melbourne"),
    (2, "Sakhir"),
    (3, "Shanghai"),
    (4, "Baku"),
    (5, "Barcelona"),
    (6, "Monte Carlo"),
    (7, "Montreal"),
    (8, "Le Castellet"),
    (9, "Spielberg"),
    (10, "Silverstone"),
    (11, "Hockenheim"),
    (12, "Budapest"),
    (13, "Spa-Francorchamps"),
    (14, "Monza"),
    (15, "Singapore"),
    (16, "Sochi"),
    (17, "Suzuka"),
    (18, "Austin"),
    (19, "Mexico City"),
    (20, "Sao Paulo"),
    (21, "Yas Marina"),
]

races_2019 = [
    (1, "Melbourne"),
    (2, "Sakhir"),
    (3, "Shanghai"),
    (4, "Baku"),
    (5, "Barcelona"),
    (6, "Monte Carlo"),
    (7, "Montreal"),
    (8, "LeCastellet"),
    (9, "Spielberg"),
    (10, "Silverstone"),
    (11, "Hockenheim"),
    (12, "Budapest"),
    (13, "Spa-Francorchamps"),
    (14, "Monza"),
    (15, "Singapore"),
    (16, "Sochi"),
    (17, "Suzuka"),
    (18, "Mexico City"),
    (19, "Austin"),
    (20, "Sao Paulo"),
    (21, "Yas Island"),
]

races_2020 = [
    (1, "Spielberg"),
    (2, "Budapest"),
    (3, "Silverstone"),
    (4, "Barcelona"),
    (5, "Spa-Francorchamps"),
    (6, "Monza"),
    (7, "Mugello"),
    (8, "Sochi"),
    (9, "Nurburgring"),
    (10, "Portimao"),
    (11, "Imola"),
    (12, "Istanbul"),
    (13, "Sakhir"),
    (14, "Yas Island"),
]

races_2021 = [
    (1, "Sakhir"),
    (2, "Imola"),
    (3, "Portimao"),
    (4, "Barcelona"),
    (5, "Monte Carlo"),
    (6, "Baku"),
    (7, "LeCastellet"),
    (8, "Spielberg"),
    (9, "Spielberg"),
    (10, "Silverstone"),
    (11, "Budapest"),
    (12, "Spa-Francorchamps"),
    (13, "Zandvoort"),
    (14, "Monza"),
    (15, "Sochi"),
    (16, "Istanbul"),
    (17, "Austin"),
    (18, "Mexico City"),
    (19, "Sao Paulo"),
    (20, "Lusail"),
    (21, "Jeddah"),
    (22, "Yas Island"),
]

races_2022 = [
    (1, "Sakhir"),
    (2, "Jeddah"),
    (3, "Melbourne"),
    (4, "Imola"),
    (5, "Miami"),
    (6, "Barcelona"),
    (7, "Monaco"),
    (8, "Baku"),
    (9, "Montreal"),
    (10, "Silverstone"),
    (11, "Spielberg"),
    (12, "LeCastellet"),
    (13, "Budapest"),
    (14, "Spa-Francorchamps"),
    (15, "Zandvoort"),
    (16, "Monza"),
    (17, "Marina Bay"),
    (18, "Suzuka"),
    (19, "Austin"),
    (20, "Mexico City"),
    (21, "Sao Paulo"),
    (22, "Yas Island"),
]

races_2023 = [
    (1, "Sakhir"),
    (2, "Jeddah"),
    (3, "Melbourne"),
    (4, "Baku"),
    (5, "Miami"),
    (6, "Monaco"),
    (7, "Barcelona"),
    (8, "Montreal"),
    (9, "Spielberg"),
    (10, "Silverstone"),
    (11, "Budapest"),
    (12, "Spa-Francorchamps"),
    (13, "Zandvoort"),
    (14, "Monza"),
    (15, "Marina Bay"),
    (16, "Suzuka"),
    (17, "Lusail"),
    (18, "Austin"),
    (19, "Mexico City"),
    (20, "Sao Paulo"),
    (21, "Las Vegas"),
    (22, "Yas Island"),
]

races_2024 = [
    (1, "Sakhir"),
    (2, "Jeddah"),
    (3, "Melbourne"),
    (4, "Suzuka"),
    (5, "Shanghai"),
    (6, "Miami"),
    (7, "Imola"),
    (8, "Monaco"),
    (9,"Montreal"),
    (10,"Barcelona"),
    (11,"Spielberg"),
    (12,"Silverstone"),
    (13,"Budapest"),
    (14,"Spa-Francorchamps"),
    (15,"Zandvoort"),
    (16,"Monza"),
    (17,"Baku"),
    (18,"Marina Bay"),
    (19,"Austin"),
    (20,"Mexico City"),
    (21,"Sao Paulo"),
    (22,"Las Vegas"),
    (23,"Lusail"),
    (24,"Yas Island"),
]