races_2018 = [
    (1, "Bahrain"),
    (2, "Saudi Arabia"),
    (3, "Australia"),
    (4, "Japan"),
    (5, "China"),
    (6, "Miami"),
    (7, "Emilia Romagna"),
    (8, "Monaco"),
    (9, "Canada"),
    (10, "Spain"),
    (11, "Austria"),
    (12, "Britain"),
    (13, "Hungary"),
    (14, "Belgium"),
    (15, "Netherlands"),
    (16, "Italy"),
    (17, "Azerbaijan"),
    (18, "Singapore"),
    (19, "USA"),
    (20, "Mexico"),
    (21, "Brazil"),
    (22, "Las Vegas"),
    (23, "Abu Dhabi"),
]

races_2019 = [
    (1, "Bahrain"),
    (2, "Saudi Arabia"),
    (3, "Australia"),
    (4, "Japan"),
    (5, "China"),
    (6, "Miami"),
    (7, "Emilia Romagna"),
    (8, "Monaco"),
    (9, "Canada"),
    (10, "Spain"),
    (11, "Austria"),
    (12, "Britain"),
    (13, "Hungary"),
    (14, "Belgium"),
    (15, "Netherlands"),
    (16, "Italy"),
    (17, "Azerbaijan"),
    (18, "Singapore"),
    (19, "USA"),
    (20, "Mexico"),
    (21, "Brazil"),
    (22, "Las Vegas"),
    (23, "Abu Dhabi"),
]

races_2020 = [
    (1, "Bahrain"),
    (2, "Saudi Arabia"),
    (3, "Australia"),
    (4, "Japan"),
    (5, "China"),
    (6, "Miami"),
    (7, "Emilia Romagna"),
    (8, "Monaco"),
    (9, "Canada"),
    (10, "Spain"),
    (11, "Austria"),
    (12, "Britain"),
    (13, "Hungary"),
    (14, "Belgium"),
    (15, "Netherlands"),
    (16, "Italy"),
    (17, "Azerbaijan"),
    (18, "Singapore"),
    (19, "USA"),
    (20, "Mexico"),
    (21, "Brazil"),
    (22, "Las Vegas"),
    (23, "Abu Dhabi"),
]

races_2021 = [
    (1, "Bahrain"),
    (2, "Saudi Arabia"),
    (3, "Australia"),
    (4, "Japan"),
    (5, "China"),
    (6, "Miami"),
    (7, "Emilia Romagna"),
    (8, "Monaco"),
    (9, "Canada"),
    (10, "Spain"),
    (11, "Austria"),
    (12, "Britain"),
    (13, "Hungary"),
    (14, "Belgium"),
    (15, "Netherlands"),
    (16, "Italy"),
    (17, "Azerbaijan"),
    (18, "Singapore"),
    (19, "USA"),
    (20, "Mexico"),
    (21, "Brazil"),
    (22, "Las Vegas"),
    (23, "Abu Dhabi"),
]

races_2022 = [
    (1, "Bahrain"),
    (2, "Saudi Arabia"),
    (3, "Australia"),
    (4, "Japan"),
    (5, "China"),
    (6, "Miami"),
    (7, "Emilia Romagna"),
    (8, "Monaco"),
    (9, "Canada"),
    (10, "Spain"),
    (11, "Austria"),
    (12, "Britain"),
    (13, "Hungary"),
    (14, "Belgium"),
    (15, "Netherlands"),
    (16, "Italy"),
    (17, "Azerbaijan"),
    (18, "Singapore"),
    (19, "USA"),
    (20, "Mexico"),
    (21, "Brazil"),
    (22, "Las Vegas"),
    (23, "Abu Dhabi"),
]

races_2023 = [
    (1, "Bahrain"),
    (2, "Saudi Arabia"),
    (3, "Australia"),
    (4, "Japan"),
    (5, "China"),
    (6, "Miami"),
    (7, "Emilia Romagna"),
    (8, "Monaco"),
    (9, "Canada"),
    (10, "Spain"),
    (11, "Austria"),
    (12, "Britain"),
    (13, "Hungary"),
    (14, "Belgium"),
    (15, "Netherlands"),
    (16, "Italy"),
    (17, "Azerbaijan"),
    (18, "Singapore"),
    (19, "USA"),
    (20, "Mexico"),
    (21, "Brazil"),
    (22, "Las Vegas"),
    (23, "Abu Dhabi"),
]

races_2024 = [
    (1, "Bahrain"),
    (2, "Saudi Arabia"),
    (3, "Australia"),
    (4, "Japan"),
    (5, "China"),
    (6, "Miami"),
    (7, "Emilia Romagna"),
    (8, "Monaco"),
    (9, "Canada"),
    (10, "Spain"),
    (11, "Austria"),
    (12, "Britain"),
    (13, "Hungary"),
    (14, "Belgium"),
    (15, "Netherlands"),
    (16, "Italy"),
    (17, "Azerbaijan"),
    (18, "Singapore"),
    (19, "USA"),
    (20, "Mexico"),
    (21, "Brazil"),
    (22, "Las Vegas"),
    (23, "Abu Dhabi"),
]